Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np

# Create a 1D array with 5 elements
arr = np.array([10, 20, 30, 40, 50])
print("Original Array:", arr)

# a) Addition of 2 in all elements
add_result = arr + 2
print("After adding 2:", add_result)

# b) Multiply 3 with all elements
mul_result = arr * 3
print("After multiplying by 3:", mul_result)

# c) Divide every element by 2
div_result = arr / 2
print("After dividing by 2:", div_result)

Original Array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
# Part a: Reverse the array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Part (a):")
print("Original Array:", arr)
print("Reversed Array:", reversed_arr)
print("-" * 40)

# Part b: Most frequent value and indices
print("Part (b):")

# i. For array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
counts_x = np.bincount(x)
most_freq_x = np.argmax(counts_x)
indices_x = np.where(x == most_freq_x)[0]

print("Array x:", x)
print(f"Most frequent value in x: {most_freq_x}")
print(f"Indices of {most_freq_x} in x: {indices_x}\n")

# ii. For array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals, counts = np.unique(y, return_counts=True)
max_count = np.max(counts)
most_freq_y = vals[counts == max_count]

print("Array y:", y)
for val in most_freq_y:
    indices_y = np.where(y == val)[0]
    print(f"Most frequent value in y: {val} (count: {max_count})")
    print(f"Indices of {val} in y: {indices_y}")

Part (a):
Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
----------------------------------------
Part (b):
Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value in x: 1
Indices of 1 in x: [0 5 7 8 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in y: 1 (count: 3)
Indices of 1 in y: [0 1 2]
Most frequent value in y: 3 (count: 3)
Indices of 3 in y: [4 8 9]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
# Create the 2D array
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("2D Array:\n", arr)

# a) Access 1st row (index 0), 2nd column (index 1)
elem_a = arr[0, 1]
print("\nElement at 1st row, 2nd column:", elem_a)

# b) Access 3rd row (index 2), 1st column (index 0)
elem_b = arr[2, 0]
print("Element at 3rd row, 1st column:", elem_b)

2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [6]:
import numpy as np

Divyadeep = np.linspace(10, 100, 25)

print("Array elements:\n", Divyadeep)
print("\nProperties of array:")
print("Dimensions (ndim):", Divyadeep.ndim)
print("Shape:", Divyadeep.shape)
print("Total elements (size):", Divyadeep.size)
print("Data type (dtype):", Divyadeep.dtype)
print("Total bytes consumed (nbytes):", Divyadeep.nbytes, "bytes")

# Transpose using reshape
transposed_reshape = Divyadeep.reshape(-1, 1)
print("\nTranspose using reshape(-1, 1):\n", transposed_reshape)

# Using .T attribute on 1D array
transposed_T = Divyadeep.T
print("\nUsing .T directly on 1D array:\n", transposed_T)

# Explanation
print("\nCan we do the same with .T attribute?")
print("No, because in NumPy a 1D array has shape (n,), so .T has no effect.")
print("To use .T as a column vector, it must first have two dimensions.")

Array elements:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Properties of array:
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200 bytes

Transpose using reshape(-1, 1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Using .T directly on 1D array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Can we do the same with .T attribute?
No, because in NumPy a 1D array has shape (n,), so .T has no effect.
To use .T as a column vector, it must first have 

Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [5]:
import numpy as np

ucs420_Divyadeep = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original 3x4 Array:\n", ucs420_Divyadeep)

# Statistical computations
print("\n--- Statistics ---")
print("Mean:", np.mean(ucs420_Divyadeep))
print("Median:", np.median(ucs420_Divyadeep))
print("Maximum:", np.max(ucs420_Divyadeep))
print("Minimum:", np.min(ucs420_Divyadeep))
print("Unique elements:", np.unique(ucs420_Divyadeep))

# Reshape the array to 4 rows and 3 columns
reshaped_ucs420_Divyadeep = ucs420_Divyadeep.reshape(4, 3)

print("\nReshaped Array (4x3):\n", reshaped_ucs420_Divyadeep)

# Resize the array to 2 rows and 3 columns
resized_ucs420_Divyadeep = np.resize(ucs420_Divyadeep, (2, 3))


print("\nResized Array (2x3):\n", resized_ucs420_Divyadeep)

Original 3x4 Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

--- Statistics ---
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
